In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [2]:
import numpy as np
import cv2

In [3]:
img=cv2.imread('/content/gdrive/My Drive/data/data1contrast.jpg')

In [6]:
# contrast
img_lab=cv2.cvtColor(img,cv2.COLOR_BGR2LAB)
l,a,b=cv2.split(img_lab)
# equ=cv2.equalizeHist(l)
# ui=cv2.merge((equ,a,b))
# hi=cv2.cvtColor(ui,cv2.COLOR_LAB2BGR)
clahe=cv2.createCLAHE(clipLimit=3.0,tileGridSize=(8,8))
cl=clahe.apply(l)
ui=cv2.merge((cl,a,b))
hi=cv2.cvtColor(ui,cv2.COLOR_LAB2BGR)
cv2.imwrite('/content/gdrive/My Drive/data/sev3_c3_contrast.jpg',hi)


True

In [4]:
img2=img.reshape((-1,3))
img2=np.float32(img2)

In [5]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)
k=6
attempts=10
ret,label,center=cv2.kmeans(img2,k,None,criteria,10,cv2.KMEANS_RANDOM_CENTERS)

In [6]:
center = np.uint8(center)
res = center[label.flatten()]
res2 = res.reshape((img.shape))

In [ ]:
cv2.imwrite('/content/gdrive/My Drive/data/data6eq.jpg',res2)

True

In [ ]:
print(res[0][0])

196


In [7]:
for i in range(label.shape[0]):
  if(label[i]==1):
    res[i]=np.array([255,255,255])
  else:
    res[i]=np.array([0,0,0])

In [ ]:
print(res)

[[196 202 208]
 [196 202 208]
 [196 202 208]
 ...
 [ 29  42  42]
 [ 29  42  42]
 [ 20  18 208]]


In [9]:
res2 = res.reshape((img.shape))
cv2.imwrite('/content/gdrive/My Drive/data/inverted.jpg',res2)

True

In [ ]:
for i in range(label.shape[0]):
  if(label[i]==2):
    res[i]=np.array([85,20,155])

In [ ]:
for i in range(label.shape[0]):
  if(label[i]==3):
    res[i]=np.array([15,165,165])

In [ ]:
for i in range(label.shape[0]):
  if(label[i]==4):
    res[i]=np.array([127,0,0])

In [ ]:
for i in range(label.shape[0]):
  if(label[i]==0):
    res[i]=np.array([0,0,0])

In [8]:
for i in range(label.shape[0]):
  if(label[i]==5):
    res[i]=np.array([9,227,247])

In [ ]:
for i in range(label.shape[0]):
  if(label[i]==6):
    res[i]=np.array([204,234,11])

In [ ]:
for i in range(label.shape[0]):
  if(label[i]==7):
    res[i]=np.array([17,82,247])

In [ ]:
for i in range(label.shape[0]):
  if(label[i]==8):
    res[i]=np.array([3,51,3])

In [ ]:
gray = cv2.cvtColor(res2, cv2.COLOR_BGR2GRAY)
cv2.imwrite('/content/gdrive/My Drive/data/finalgrey.jpg',gray)

True

In [ ]:
# ret, thresh = cv2.threshold(gray, 127, 255, 0)
contours, hierarchy = cv2.findContours(gray, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)

In [ ]:
print(len(contours))

571


In [ ]:
gray2=gray

In [ ]:
x=cv2.drawContours(gray2, contours, -1, (42,255,64), 3)

In [ ]:
gray.shape

(567, 800)

In [ ]:
cv2.imwrite('/content/gdrive/My Drive/data/canny.jpg',edges)

True

In [ ]:
edges=cv2.Canny(gray,100,200)

In [20]:
# for changing to binary
img=cv2.imread('/content/gdrive/My Drive/data/segd5.jpg')
print(img[])

(753, 871, 3)


In [25]:
for i in range(img.shape[0]):
  for j in range(img.shape[1]):
    if(img[i][j][0]==9 and img[i][j][1]==227 and img[i][j][2]==247):
      img[i][j]=[0,0,0]
    else:
      img[i][j]=[255,255,255]

print(img)


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [26]:
cv2.imwrite('/content/gdrive/My Drive/data/segd5_binary.jpg',img)

True